# 参考
# https://github.com/Azure/arm-deploy
# https://github.com/Azure/cli

name: Azure Bicep Deployment.

# トリガーを指定
on:
  # プッシュ
  push:
    branches:
      - main
      - develop

  # 手動
  workflow_dispatch:

permissions:
  id-token: write
  contents: read

env: # 環境変数
  APP_NAME: ${{ vars.APP_NAME }}
  SUFFIX: ${{ vars.SUFFIX }}

jobs:
  deploy:
    runs-on: ubuntu-latest

    # 環境選択
    environment: ${{ github.ref_name == 'main' && 'Production' || github.ref_name == 'develop' && 'Development'}}

    env: # 環境変数
      APP_ENVIRONMENT: ${{ vars.APP_ENVIRONMENT }}

    steps:
      # チェックアウト
      - name: Checkout to the branch
        uses: actions/checkout@v4

      # Azure ログイン
      - name: Azure Login
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}


      # リソースデプロイ
      - name: Deploy with Azure Bicep
        # uses: azure/arm-deploy@v1
        # with:
        #   resourceGroupName: ${{ secrets.AZURE_RESOURCE_GROUP_NAME }}
        #   subscriptionId: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
        #   template: ./infra/main.bicep
        #   parameters: ./infra/main.bicepparam
        #   deploymentMode: Incremental
        #   deploymentName: Deploy_${{ env.APP_NAME }}
        #   failOnStdErr: true

        uses: azure/cli@v2
        with:
          azcliversion: latest
          inlineScript: |
            az deployment group create \
              --name Deploy_${{ env.APP_NAME }} \
              --resource-group ${{ secrets.AZURE_RESOURCE_GROUP_NAME }} \
              --template-file infra/main.bicep \
              --parameters infra/main.bicepparam
