# 参考
# https://github.com/Azure/arm-deploy

name: Azure Bicep Deployment.

# トリガーを指定
on:
  # プッシュ
  push:
    branches:
      - main
      - develop

  # 手動
  workflow_dispatch:

permissions:
  id-token: write
  contents: read

env: # 環境変数
  APP_NAME: ${{ vars.APP_NAME }}
  SUFFIX: ${{ vars.SUFFIX }}

jobs:
  deploy:
    runs-on: ubuntu-latest

    # 環境選択
    environment: ${{ github.ref_name == 'main' && 'Production' || github.ref_name == 'develop' && 'Development'}}

    env: # 環境変数
      APP_ENVIRONMENT: ${{ vars.APP_ENVIRONMENT }}
      AZURE_RESOURCE_GROUP_NAME: ${{ vars.AZURE_RESOURCE_GROUP_NAME }}


    steps:
      # チェックアウト
      - name: Checkout to the branch
        uses: actions/checkout@v3
        with:
          path: repo

      # Azure ログイン
      - name: Azure Login
        uses: azure/login@v1
        with:
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}

      # リソースデプロイ
      - name: Deploy
        uses: azure/arm-deploy@v1
        with:
          resourceGroupName: ${{ env.AZURE_RESOURCE_GROUP_NAME }}
          template: ./infra/main.bicep
          parameters: ./infra/main.bicepparam
          deploymentMode: Incremental
          deploymentName: Deploy_${{ env.APP_NAME }}
          failOnStdErr: true
